################################################################################
# modeling.R
#   This script contains the modelling logic employed in this simulation
#
# @author: Hair Parra
################################################################################

################
### 0. Setup ###
################

# load required scripts
library("here") 
source(here("functions", "fetch_sp500_sectors.R")) # functions for top stocks and economic sectors in the sp500
source(here("functions", "feature_engineering.R")) # functions for feat eng and manipulation

###########################
### 1. Modelling Logic  ###
###########################

f_MODELLING_PROCEDURE <- function(G, tau, sp500_stocks, best_n = 3){
  ### This function does the following: 
  ##    - Extracts the appropriate window of data for all stocks in the sector 
  ##    - Computes dynamic features for all stocks in the sector 
  ##    - Loops through every ticker, performing feature selection, hyperparameter 
  ##      tuning and model selection, produces forecasts and calculates a number of metrics. 
  ##    - Store the result in an object `sector_tracker`
  ##    - Chooses the best n stocks based on two criteria: best forecasted returns, 
  ##      and best historical Sharpe Ratio. 
  ##
  ## Returns: 
  ##    - top_sector_stocks (named list)
  NULL
}

############################
### 2. Best Tickers Data ###
############################

## TODO: Complete the function, keep the name and parameters 
f_select_top_stocks <- function(sector_tracker, n=3){
  ## selects the top n + n stocks (n based on forecasted return, n based on sharpe)
  ##
  ## Params: 
  ##    - sector_tracker (list of lists): generated by the Loop for every stock ticker in sector G 
  ##    - n (int): number of top stocks to choos efor each method. Top n for the predicted returns, 
  ##              and top n for the sharpe-based. 
  
  # Extract the top 3 tickers with the highest Sharpe ratio
  top_sharpe <- names(sort(sapply(sector_tracker, function(x) x$sharpe), decreasing=TRUE))[1:n]
  top_fore_rets <- names(sort(sapply(sector_tracker, function(x) x$forecasted_ret), decreasing=TRUE))[1:n]
  
  # Concat in one list 
  top_tickers  <- union(top_sharpe, top_fore_rets) 
  
  # Create a new named list with tickers and their corresponding data
  best_stocks_data <- sector_tracker[top_tickers]
  
  return(best_stocks_data)
}