f_select_top_stocks <- function(sector_tracker, n=3){
  ## selects the top n + n stocks (n based on forecasted return, n based on sharpe)
  ##
  ## Params: 
  ##    - sector_tracker (list of lists): generated by the Loop for every stock ticker in sector G 
  ##    - n (int): number of top stocks to choose for each method. Top n for the predicted returns, 
  ##              and top n for the sharpe-based. 
  
  # Extract the predicted mean return and the Sharpe Ratio from sector_tracker
  forecasted_ret <- sapply(sector_tracker, function(x) x$forecasted_ret)
  sharpe_metric <- sapply(sector_tracker, function(x) x$sharpe)
  

  # Identify the top n stocks based on forecasted return and sharpe metric
  top_ret_indices <- order(forecasted_ret, decreasing = TRUE)[1:n]
  top_sharpe_indices <- order(sharpe_metric, decreasing = TRUE)[1:n]
  
  # Get the ticker names for the top stocks
  top_ret_tickers <- names(forecasted_ret)[top_ret_indices]
  top_sharpe_tickers <- names(sharpe_metric)[top_sharpe_indices]
  
  # Select the data for the top stocks from sector_tracker
  top_ret_stocks <- sector_tracker[top_ret_tickers]
  top_sharpe_stocks <- sector_tracker[top_sharpe_tickers]
  
  
  # Combine the lists of top stocks based on Forecasted return and Sharpe Ratio
  combined_names <- unique(c(top_ret_tickers,top_sharpe_tickers ))
  combined_tickers <- unique(c(top_ret_tickers, top_sharpe_tickers))
  
  best_stocks <- list()
  
  for(ticker in combined_tickers) {
    best_stocks[[ticker]] <- sector_tracker[[ticker]]
  }
  
  return(list(combined_names = combined_names, best_stocks = best_stocks))
}


